export const ENVIRONEMNT_KEYS = {
    ENV: 'REACT_APP_ACTIVE_ENVIRONMENT',
    GOOGLE_AUTHENTICATION_CLIENT_ID: 'REACT_APP_GOOGLE_CLIENT_ID'
}

export const ENVIRONEMNTS = {
    LOCAL: 'local',
    DEVELOPMENT: 'dev',
}